### ISSUE TITLE
Update site is not working

### ISSUE THREAD

**Issue by natzei** [eclipse/xsemantics#101]
The update site https://dl.bintray.com/lorenzobettini/xsemantics/updates/ isn't working. Every file request returns an HTTP 403 (forbidden).

**Comment by LorenzoBettini** [comment]
I'm aware of that, due to some problems with my bintray account...

The new milestones of Xsemantics, as an Eclipse project, can be found here:

https://ci.eclipse.org/xsemantics/job/xsemantics-nightly/lastSuccessfulBuild/artifact/releng/org.eclipse.xsemantics.repository/target/repository/

please keep in mind that now all artifacts start with org.eclipse.xsemantics instead of it.xsemantics.

**Comment by natzei** [comment]
Thank you! I reinstalled xsemantics. Everything is working within eclipse. 
However, maven cannot build due to the (now obsolete) artifacts. Maven central only contains `net.sf.xsemantics:it.xsemantics.dsl`. Is there any maven repository I can setup in my pom?

**Comment by LorenzoBettini** [comment]
Sorry, but since for the moment there's no official Eclipse Xsemantics release yet (only milestones update sites), no Maven artifacts for the Eclipse Xsemantics are yet available... you could still use the old net.sf.xsemantics:it.xsemantics.dsl Maven artifact if you need to compile Xsemantics files during the Maven build, it should still work.

**Comment by natzei** [comment]
In that case, I'll not be able to build within eclipse, since the "old" xsemantics cannot be installed. Is there any chance to get the old update site working?

**Comment by LorenzoBettini** [comment]
I'm not sure I understand... why do you need Maven artifacts in Eclipse?

**Comment by natzei** [comment]
I don't. I configured Eclipse with the new update site, so I changed all the imports of it.xsemantics to org.eclipse.xsemantics. Eclipse builds correctly. However, maven build does not work, because it uses the old packaging it.xsemantics.

So I'd like to revert my changes: uninstall org.eclipse.xsemantics and install it.xsemantics, in order to get both Eclipse and Maven build working. But the old update site isn't working.

Thanks a lot for your help!

**Comment by LorenzoBettini** [comment]
Oh I see... well I still don't know about the time of the first Eclipse release... note that the problem bintray is temporary (hopefully :)

**Comment by natzei** [comment]
Ok, then I'll wait patiently. Thank you!

**Comment by LorenzoBettini** [comment]
The bintray update site is back online! :)

**Comment by bitcoin-transaction-model** [comment]
I'm updating right now :) Thanks again for your help!

**Comment by natzei** [comment]
I'm updating right now :) Thanks again for your help!
