### ISSUE TITLE
Why SNAPSHOT releases are the only one available?

### ISSUE THREAD

**Issue by natzei** [eclipse/xsemantics#119]
Hi all, I'm wondering why Xsemantics still have only SNAPSHOT releases and doesn't have "stable" ones. Could it cause some limitations in the Maven build phase?

Some time ago I tried removing the "-SNAPSHOT" from the version of my project and I remember tycho was complaining that I cannot use dependencies that are SNAPSHOT releases, Xsemantics in this case.

**Comment by LorenzoBettini** [comment]
Sorry, we are still working on the official release process... I hope we'll get something ready soon.

**Comment by LorenzoBettini** [comment]
In the Maven build phase, if you're using Tycho, it should be no problem. There might be problems if you use Maven to perform a release of Maven artifacts since the process requires all dependencies NOT to be snapshots... I think this could be forced, but I'm not sure... if you are not deploying Maven artifacts then you're fine

**Comment by natzei** [comment]
You're right, I experimented removing the -SNAPSHOT suffix using the tycho-versions plugin and the project built correctly. Thanks for your reply :)
