### ISSUE TITLE
Xsemantics no longer referenced by Sonatype Snapshot repository index

### ISSUE THREAD

**Issue by vhemery** [eclipse/xsemantics#124]
Hello,
Since yesterday (or earlier), it looks like the https://oss.sonatype.org/content/repositories/snapshots/ repository index no longer reference Xsemantics artefacts.
On a maven build that used to pass, I get 
[WARNING] The POM for org.eclipse.xsemantics:org.eclipse.xsemantics.dsl:jar:1.16.0-SNAPSHOT is missing, no dependency information available
then an error, and I can't find a trace of xsemantics in 
https://oss.sonatype.org/content/repositories/snapshots/archetype-catalog.xml
I worked around the problem in my Nexus by referencing directly the site
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xsemantics/org.eclipse.xsemantics.dsl/
Is Sonatype Snapshot still the official maven artifacts repository or is it going to change ? Is there any explanation to the fact that the index has lost track of Xsemantics artifacts ?

**Comment by LorenzoBettini** [comment]
Hi
there's never been trace of xsemantics in the archetype-catalog since that's only the catalog of archetypes and xsemantics does not provide one...

everything seems to work fine from my side and everything seems to be in place on sonatype:
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xsemantics/

maybe you have a corrupt local Maven repository?
Could you please try to remove xsemantics directories from your local `.m2`?

**Comment by vhemery** [comment]
I did... Now, I have an issue on Xtend and guava... Then after upgrading Xtend to 2.17 and Xsemantics to 1.17, it tells me it can't find Xsemantics 1.17 though it has been correctly downloaded to my Nexus...

So yeah, I guess the problem is definitely only on my side. Thank you for your reply.
