### ISSUE TITLE
Error when using Xsemantics in maven/tycho build

### ISSUE THREAD

**Issue by lwrage** [eclipse/xsemantics#156]
The pom file for org.eclipse.xsemantics.dsl seems to have an error that leads to a failure when running xsemantics during a tycho build. The following dependency is marked with an error when I open the pom file from the maven repo in Eclipse: _'dependencies.dependency.systemPath' for p2.p2.installable.unit:org.eclipse.rcp_root:p2-installable-unit is missing._ 
```
    <dependency>
      <groupId>p2.p2.installable.unit</groupId>
      <artifactId>org.eclipse.rcp_root</artifactId>
      <version>4.22.0.v20211124-1800</version>
      <type>p2-installable-unit</type>
      <scope>system</scope>
      <optional>false</optional>
    </dependency>
```

The same error is in the pom file for org.eclipse.xsemantics.runtime, but that one does not lead to a build failure. I deleted the dependency in my local local copy of the pom file to make my build work.

**Comment by LorenzoBettini** [comment]
Yes, unfortunately there was a change in Tycho 2.7 that broke all my released Maven artifacts, including Xsemantics https://github.com/eclipse/tycho/issues/781

I'll try to release new versions of the artifacts now that I know how to do that (I'll release a new 1.22 I guess, since what's already deployed on Maven Central cannot be updated).

I'm terribly sorry about the inconvenience... it used to work with previous versions of tycho

**Comment by LorenzoBettini** [comment]
Actually, I'm releasing Maven snapshots, so I can simply deploy a new snapshot, without increasing the version :)

**Comment by LorenzoBettini** [comment]
OK, I'll release updated snapshots (still 1.21), so the problem should be fixed if you start your CI again!

**Comment by lwrage** [comment]
My build is back to normal. Thanks!
