### ISSUE TITLE
Judgement cache not cleared when change occurs to cross-reference in other resource

### ISSUE THREAD

**Issue by SimonCockx** [eclipse/xsemantics#180]
For now this is more of a question than an issue, I think.

In the Rosetta DSL, there exists an issue where changes to a type in one file are not propagated to other files. I wonder whether this has to do with the fact that Xsemantics uses a resource-scoped caching mechanism under the hood.

## Illustrative pseudo code example

File 1:
```
// Define a class with one attribute of type `int`.
class A:
   attribute int
```

File 2:
```
// import file 1

// Define a function with a parameter of type `A` which returns an `int`.
function Foo(input A) -> int:
  return input.attribute
```

The type checker passes at this point, as it should.

Now change the type of `attribute` to `string` in File 1:
```
class A:
   attribute string
```

Type checking in File 2 is not triggered again until I make a change there, so it looks like there is no type error, although there should be.

Do you think this is an issue in Xsemantics?

**Comment by LorenzoBettini** [comment]
Hi

are you using caching in your type system? If so, please try to disable it temporarily and see whether the problem is still there.

However, what you see might be due to the standard Xtext mechanism concerning understanding whether a change in a resource affects something in another resource (e.g., the contained body in your case). You might want to check (debug) how Xtext detects whether a resource is affected by a change in another resource and, in case, customize it.

**Comment by SimonCockx** [comment]
Thanks for the prompt response. I don't have any explicit caching enabled. Just to get this clear for me: Xsemantics does not do any caching on its judgements by default? Then I can tick that off my list of things to debug first. :)

> However, what you see might be due to the standard Xtext mechanism concerning understanding whether a change in a resource affects something in another resource (e.g., the contained body in your case).

This might be very well it, thanks for the pointer.

**Comment by LorenzoBettini** [comment]
The generated Java code from Xsemantics does not do any caching by default.

**Comment by SimonCockx** [comment]
Thanks for the info. I'll close this then.
